### PR TITLE
CI: Cache the test data + optimize dnf install + add tox + rawhide

### PR DESCRIPTION
**Pull request by hroncok**
See individual commits

### CODE REVIEW

**Review by gordonmessmer — APPROVED** [review]
All of this looks good to me.

**Comment by hroncok** [comment]
Thanks. I'll merge from the command line.

**Comment by hroncok** [comment]
There's a problem with the py38 tox job. It cannot download the test data and it hasn't show up before here, bacause in my fork they were cached from a different Python version. I'll send a fix later, but not sure if today, I am away from my computer, typing from phone. To reproduce, I think one needs to delete the local test data and run tox -e py38.

**Comment by hroncok** [comment]
https://github.com/rpm-software-management/python-rpm-packaging/pull/11

**Pull request merged**
